[features]
seeds = false

[programs.localnet]
solana_twitter = "7FHgrsjmeRzey47RTC3fy8pQzLkQ5Ci837husXZExa1V"

[programs.devnet]
solana_twitter = "7FHgrsjmeRzey47RTC3fy8pQzLkQ5Ci837husXZExa1V"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/daniecon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"
